import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import type { ReactElement } from "react";
import { useEffect, useState } from "react";

export default function Layout({ children }: { children: ReactElement }) {
    const router = useRouter();
    const { type } = router.query;
    const [showBackBtn, setShowBackBtn] = useState(false);

    useEffect(() => {
        setShowBackBtn(Boolean(type));
    }, [type]);

    return (
        <>
            <Head>
                <title>ArcGIS T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col h-screen">
                <header
                    className="sticky top-0 z-30 w-full px-2 py-4 text-[#FFFFFF] bg-[#007AC2] shadow-xl">
                    {showBackBtn && <Link href="/">{`<`}</Link>}
                    <span className="mx-5">ArcGIS NextJS</span>
                </header>
                <main className="flex h-full flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                    <div className="h-full w-full flex flex-col items-center justify-center">
                        {children}
                    </div>
                </main>
            </div>
        </>
    );
}
