import Head from "next/head";
import type { ReactElement } from "react";

export default function Layout({ children }: { children: ReactElement }) {

    return (
        <>
            <Head>
                <title>Create T3 ArcGIS App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col h-screen">
                <header className="sticky top-0 z-30 w-full px-2 py-4 text-[#FFFFFF] bg-[#007AC2]">
                    <span className="mx-5">ArcGIS NextJS</span>
                </header>
                <main className="flex h-full flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                    <div className="h-full w-full flex flex-col items-center justify-center">
                        {children}
                    </div>
                </main>
            </div>
        </>
    );
}

